all: ejercicio1 ejercicio2 ejercicio3 ejercicio4
  .PHONY: all

ejercicio1:
	gcc -pthread Ejercicio1/ej1.c -lm
	./a.out
	rm a.out
ejercicio2:
	gcc -pthread Ejercicio2/ej2.c -lm
	./a.out
	rm a.out
ejercicio3:
	gcc -pthread Ejercicio3/ej3.c
	./a.out 10
	rm a.out
ejercicio4:
	gcc -pthread Ejercicio4/ej4.1.c
	./a.out 10
	echo -----------------------
	gcc -pthread Ejercicio4/ej4.2.c
	./a.out 10
	rm a.out
